#!/bin/sh
# Joins src/*.js into dist/Code.gs, a single file to paste into the Apps Script editor.
# Apps Script runs all files in one global scope, so one file behaves the same.
set -eu
cd "$(dirname "$0")"
mkdir -p dist
{
  echo "// Statuser, generated by bundle.sh from src/. Don't edit by hand."
  for f in Config Logic Settings SettingsPage Calendar Slack Main; do
    printf '\n// ---- %s.js ----\n\n' "$f"
    cat "src/$f.js"
  done
} > dist/Code.gs
